### ISSUE TITLE
Results are different from both the paper and the source code when reproducing the paper

### ISSUE THREAD

**Issue by Claire-ui** [chufangao/TTM-RE#7]
The paper shows that with 4 layers and a memory capacity of 200, the results are (84.01±0.23, 83.11±0.20, 86.03±0.18, 82.09±0.30), while the output from the source code download shows the results as {"test_F1": 83.6041966673524, "test_F1_ign": 82.67186522190119, "re_p": 85.79528318957718, "re_r": 81.52223750573133}. However, without changing any settings, using seed 74 for local pre-training and fine-tuning results in {"test_F1": 82.87447503499766, "test_F1_ign": 81.8735115791882, "re_p": 84.37054631828978, "re_r": 81.43053645116919}. May I ask if the author is aware of the reasons behind this discrepancy? I would greatly appreciate any clarification. Additionally, I encountered an error when trying to run the released model:

S-PU 1
PRETRAINING
pretrain distant 4
pretrain performance {'test_F1': 0.20732121065507314, 'test_F1_ign': 0.17894695194501686, 're_p': 0.10407660590202907, 're_r': 25.934204493351675}
FINETUNING
TEST
Traceback (most recent call last):
  File "train2.py", line 527, in <module>
    main()
  File "train2.py", line 505, in main
    model.load_state_dict(torch.load(os.path.join(args.save_path, "finetune_state_dict.pth")))
  File "/home/liusl/anaconda3/envs/dreeam/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DocREModel:
        Missing key(s) in state_dict: "model.embeddings.position_ids". 

The error message indicates that the released model is missing some structures. Therefore, I performed an MD5 binary check on the model (md5sum finetune_state_dict.pth), and the result is:
bc8cde05d2a74e735c0eac7a08f91234 finetune_state_dict.pth. Could you please help check if there was an issue with my model download?
Additionally, the results above show that the downloaded pre-trained model has an F1 of only 0.207, while the pre-training results on my local fine-tuning show (seed 72: F1 62.37; seed 66: F1 55.65). Finally, the paper mentions that the final results were obtained by running with 5 different seeds. Could the author kindly provide the specific list of seeds used in the paper?

**Comment by Abokhatwa** [comment]
I also have the same issue. The results after finetuning are: {'test_F1': 82.88673063421484, 'test_F1_ign': 81.88632547781182, 're_p': 84.64985659655831, 're_r': 81.19555249885374}. If they could please provide any clarifications, I would appreciate it.
